version: '3.8'

services:
  # Oracle Database
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: sqli_oracle_db
    environment:
      - ORACLE_PWD=OraclePassword123
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./database/oracle-setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - sqli-network
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/OraclePassword123@//localhost:1521/XEPDB1", "as", "sysdba", "@", "/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Spring Boot Application
  spring-boot-app:
    build:
      context: ./spring-boot
      dockerfile: Dockerfile
    container_name: sqli_spring_boot
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=sqli_lab
      - SPRING_DATASOURCE_PASSWORD=SqliLab123!
    depends_on:
      oracle-db:
        condition: service_healthy
    networks:
      - sqli-network
    restart: unless-stopped

  # .NET Core Application
  dotnet-app:
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    container_name: sqli_dotnet_app
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=oracle-db:1521/XEPDB1;User Id=sqli_lab;Password=SqliLab123!;Connection Timeout=30;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      oracle-db:
        condition: service_healthy
    networks:
      - sqli-network
    restart: unless-stopped

volumes:
  oracle_data:

networks:
  sqli-network:
    driver: bridge
