services:
  php-lab:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003
    volumes:
      - .:/var/www
      - /var/www/vendor
      - /var/www/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: bridge
    command: ["debug"]
    restart: unless-stopped
